### ISSUE TITLE
Assignment 8-2 - JS Frameworks

### ISSUE THREAD

**Issue by ambethia** [grayswan/Assignments#28]
# The Right Tool for the Job

This week you were introduced to both React and Angular. I'd like you to read this article and reflect on it. Share your thoughts in a post on your blog (or in a private gist) and link it here.

https://www.lullabot.com/articles/choosing-the-right-javascript-framework-for-the-job

**Comment by grayswan** [comment]
https://medium.com/@swan.kristen/the-right-stuff-ca842ae93ad8
