### ISSUE TITLE
Assignment 2-1 - HTML/CSS Basics

### ISSUE THREAD

**Issue by ambethia** [grayswan/Assignments#5]
## HTML/CSS Basics
- [ ] Read [this article](http://blog.froont.com/brief-history-of-web-design-for-designers/) on the history of web design.
- [ ] Compose a short (a few paragraphs) blog that summarizes your thoughts on the web; where's it's been an where it's going.
- [ ] Create an HTML document that contains your blog. It should have a title, a byline and the article itself.
### Explorer Mode
- [ ] Mark up your document with valid HTML.
- [ ] Use at least 12 different HTML tags.
- [ ] Add at least one image to your page.
- [ ] Use valid CSS to style the page.
- [ ] Research the `id` and `class` HTML attributes.
- [ ] Use at least 12 CSS statements to style the page (a statement includes a selector and a number of properties). Try to use `id` and `class` attributes in your CSS selectors where relevant.
- [ ] All of your HTML and CSS should be formatted cleanly and consistently.
### Adventure Mode
- [ ] Use more complex CSS selectors than we covered in class.
- [ ] Use at least 24 CSS statements.
- [ ] Use at least one background image (with CSS) somewhere on the page.
### Epic Mode
- [ ] Create a full "Blog" layout for your page (heading, navigation, sidebar, footer, etc.).
## Additional Resources
- https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
- http://atozcss.com/start-here/
- http://www.evolutionoftheweb.com

**Comment by grayswan** [comment]
I completed this assignment, but cannot get it to push to github. I keep getting fatal: remote origin already exists. I don't know what's going on.

**Comment by ambethia** [comment]
We'll review git again today.

**Comment by grayswan** [comment]
FINALLY! I had to remove origin. 

https://github.com/grayswan/HTML-CSS-Basics

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/pkXLdrjSQNt1m/200w_d.gif)
